### ISSUE TITLE
`reset()` should not trigger validation errors

### ISSUE THREAD

**Issue by websocket98765** [pablo-abc/felte#10]
After submitting a form and receiving the response, I call `reset()`. It clears the input values as expected, but it also triggers _all_ inputs to show their validation errors & shouldn't. 

(I'm using DOM reporter, yup, & have required values for all inputs in my form as part of the yup validation.)

```js
 if (res.status === 200) {
    reset();
 }
```

**Comment by pablo-abc** [comment]
Thanks for the heads up! Fixed in [felte@0.5.5](https://github.com/pablo-abc/felte/blob/main/packages/felte/CHANGELOG.md#055)
