### ISSUE TITLE
[validator-zod]  Build result is broken.

### ISSUE THREAD

**Issue by KoichiKiyokawa** [pablo-abc/felte#100]
First, thank you for felte v1 👏 
I found that the esm build result of `@felte/validator-zod` is broken 🤔 

<img width="649" alt="image" src="https://user-images.githubusercontent.com/40315079/154074223-0cb22f88-a980-4683-b8b8-e8c15bfb37b7.png">

Repro:
```bash
git clone https://github.com/pablo-abc/felte.git
pnpm i
pnpm run build
```

**Comment by pablo-abc** [comment]
Whoops! Should be fixed now if you pull from the latest changes!

**Comment by KoichiKiyokawa** [comment]
I confirmed this issue was fixed by https://github.com/pablo-abc/felte/commit/34ecc4678f43fd43a96d248c0acc31a3542e04ff !
Thank you very much!
