### ISSUE TITLE
Docs->Migrating->Helpers — typo in first example

### ISSUE THREAD

**Issue by nimmolo** [pablo-abc/felte#102]
Congratulations on 1.0.0!! 🙌

Minor typo: In the [first example](https://felte.dev/docs/svelte/migrating#helpers), after "should now be", i believe it should be `setFields`:

![Screen Shot 2022-02-23 at 12 23 22 PM](https://user-images.githubusercontent.com/1948095/155402003-e2def20e-7c72-4685-a24c-c3ea26c1259d.png)

**Comment by pablo-abc** [comment]
Thanks a lot! And good catch!

This is fixed now 😊
