### ISSUE TITLE
Use zod@3.0.0 as peer dep

### ISSUE THREAD

**Issue by websocket98765** [pablo-abc/felte#11]
Could we use zod `^3.0.0` as the peer dep? 

When running `npm i -D zod`, it installs `zod@3.0.0-alpha.33`. I tested `^3.0.0` as the peer dep and it works.

Currently, I hit an error due to version mismatch:
```sh
Found: zod@3.0.0-alpha.33
npm ERR! node_modules/zod
npm ERR!   dev zod@"^3.0.0-alpha.33" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer zod@"^1.11.13" from @felte/validator-zod@0.2.0
```

(I also noticed my vite error was resolved by removing zod and re-install using `npm i -D zod` as a devDependency. So we might want to update https://felte.dev/docs#using-zod)

**Comment by pablo-abc** [comment]
The reason I didn't go for zod@^3.0.0 is that it is still in alpha. I'm not sure if it is "production ready" yet so breaking changes in Zod 3 will also mean breaking changes in Felte. I'm not against of publishing a version with Zod v3 as a prerelease like `@felte/validator-zod@next`. Is Zod 3 the recommended version to be using now or are they still recommending to go with v1 until v3 is ready?

**Comment by websocket98765** [comment]
You're right. `1.11.13` is installed by `npm i zod`. My 3.x.x was from my troubleshooting apparently.

Yours is a reasonable choice. I'll just `npm update --force` to avoid a peer dep error for now. 3.0.0 works well with your Felte adapter incidentally.
