### ISSUE TITLE
Error with ts for use:form

### ISSUE THREAD

**Issue by Arthurmtro** [pablo-abc/felte#113]
**Describe the bug**
(property) use:form: true
Type '{ children: Element[]; "use:form": true; }' is not assignable to type 'FormHTMLAttributes<HTMLFormElement>'.
  Property 'use:form' does not exist on type 'FormHTMLAttributes<HTMLFormElement>'

![image](https://user-images.githubusercontent.com/55857849/158082250-2805e2ca-4b05-4ac7-9965-c435d19476e9.png)

**Comment by pablo-abc** [comment]
I haven't found a way to "package" the type definition for this, and I haven't found any other Solid library that does for now. For now I recommend what Solid's documentation recommends: [extending the JSX namespace yourself]((https://www.solidjs.com/docs/latest/api#special-jsx-attributes). Adding this to a `d.ts` file and pointing to it using `tsconfig.json`'s typeRoots works for me:

```typescript
import 'solid-js';
declare module 'solid-js' {
  namespace JSX {
    interface Directives {
      form: true;
    }
  }
}
```

**Comment by pablo-abc** [comment]
I'm closing this since what I commented should solve your issue!

**Comment by MarvinRudolph** [comment]
@pablo-abc 
Hey! Shouldn't it be possible to expose it as a separate entry in `exports` of the `package.json` so it can be included in TS projects similar to Vite's `vite/client` types
(see here https://github.com/vitejs/vite/blob/main/packages/vite/package.json#L21)?

I mean something like this:
**solid/types.d.ts**

```ts
declare module "solid-js" {
  namespace JSX {
    interface Directives {
      form: true;
    }
  }
}
```

**package.json**

```json
"exports": {
    ".": {
      "import": "./dist/esm/index.js",
      "require": "./dist/cjs/index.cjs",
      "default": "./dist/esm/index.js"
    },
    "./package.json": "./package.json",
    "./types": {
       "types": "./types.d.ts"
     }
}
```

Then you should be able to add those types with this in a `.d.ts` file
```ts
/// <reference types="@felte/solid/types" />
```
or in the tsconfig.json
```json
{
  "compilerOptions": {
    "types": ["@felte/solid/types"]
  }
}
```

**Comment by rob-forager** [comment]
For those of you stumbling across this, the changes you need to make to `tsconfig.json`
```javascript
{
  "compilerOptions": {
    // ...
    "typeRoots": [
      "path/to/types",
      // ...
    ],
    // ...
  },
  "files": [
    // ...
    "path/to/types/filename.d.ts"
  ],
}
```
Without the `"files"` part it was just completely ignoring the change.
