### ISSUE TITLE
Tippy reporter memory leak

### ISSUE THREAD

**Issue by ambiguous48** [pablo-abc/felte#115]
First, a big thank you for this package. From it's usage all the way to the docs, Felte is a delight to use.

**Describe the bug**
I have a use case where I need to recalculate an array of fields based on an external input. Using the tippy reporter in this scenario causes a huge delay. The delay increases very noticeably as the length of the list increases. At around 10 items, the delay is more than a second.

P.S. Don't set the item count to a very large number (risk of crashing).

**To Reproduce**
Increast the counter slowly to see the delay. The browser console might also display a tippy warning about a memory leak.
```html
<script>
  import { createForm } from 'felte';
  import reporter from '@felte/reporter-tippy';

  const { form } = createForm({
    extend: reporter() // <-- Delete this to remove lag.
  });

  let count = 1;
  $: interests = Array.from({ length: count }, () => ({ price: Math.random() * 1000 }));
</script>

<p>Item Count:</p>
<input type="number" bind:value={count} />

<p>Items:</p>
<form use:form>
  {#each interests as interest, index (interest.price)}
    <div>
      <input name="interests.{index}.value" value={interest.price} />
    </div>
  {/each}
</form>
```

![image](https://user-images.githubusercontent.com/33713262/158497051-48d26246-1ba8-4512-859a-7e020399e69b.png)

**Environment (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: [felte@1.1.3, @felte/reporter-tippy@1.0.3, tippy.js@6.3.7]

**Comment by pablo-abc** [comment]
Thanks a lot! I'll look into this.

Curiously enough, the delay is _way_ less dramatic if you remove the key from the `#each` (the `(interest.price)`).

**Comment by ambiguous48** [comment]
If I remove the `(interest.price)` key, would there be another way to refresh existing list elements?

For example:
1. Change one of the prices manually to `99`.
2. Increase the counter.
3. a. (with key) (desired behavior) The `99` you entered in step 1 will be overriden.
b. (without key) The `99` will remain.

**Comment by pablo-abc** [comment]
If the values are managed by Felte then the value would remain consistent In the case of your REPL you're regenerating the whole list/values regardless of if there was a previous value on it. So behaviour `a` seems to be happening regardless?

The other thing is that you _shouldn't_ use `price` as a key. The key should _always_ be unique, and remain consistent even if the value of the input changes. This is not the case here so it's perfectly ok to leave that empty. And if you want to override its value then doing what you're doing `value={interest.price}` should always prevent the previous value from remaining.

---

Regardless, I do believe there's a memory leak and I _think_ I found where it's happening. But I need to do some digging.

**Comment by pablo-abc** [comment]
Performance should have greatly improved on `@felte/reporter-tippy@1.0.5` and `felte@1.1.4`. I'm starting to get lag at around 1000 elements using reporter-tippy and without it, there's some lag but it's still useable when you start to get close to 10,000 elements. There might be more improvements to be made regarding performance, but this solves the main issue right now!
