### ISSUE TITLE
Remove an error after form.setErrors

### ISSUE THREAD

**Issue by jcalfee** [pablo-abc/felte#123]
### Describe the bug

I running client-side and have the '@felte/reporter-svelte' `ValidationMessage` showing an error after I call `form.setErrors(cmpName, 'Invalid')` where cmpName using the dot notation.  For some reason, I can't remove the error using `form.setErrors(cmpName, null)`.  I also noticed that if I try to change the error using `form.setErrors(cmpName, 'Valid')` that does not work either.  I'm using the same syntax as the docs.  
```svelte
<ValidationMessage for={cmpName} let:messages={messages}>
  <div>{messages?.[0] || ''}</div>
</ValidationMessage>
```

I tried to follow the code but I get lost in the createSetHelper.  Is this expected behavior?  How can I update or remove the error message in this case?

### Which package/s are you using?

felte (Svelte)

### Environment

- @felte/reporter-svelte ^1.0.3
- felte ^1.1.4

**Comment by pablo-abc** [comment]
Do you have a reproduction of what you're trying to do? Setting the error value to `null` works for me. And that'd be how to remove an error (forcefully setting a field to be valid).
Btw, if the purpose is to just stop displaying the validation message but still keeping the field as invalid, it'd be better to use `setTouched('fieldName', false)`.

**Comment by jcalfee** [comment]
Thanks for the confirmation.  It becomes valid so null is what I need.  NIce to have that option with "touched" so I'm keeping that in mind.  I apologize, I just added some code in that area to support 'warn' and re-tested and it is working just like you said.  Not sure what happened, I tested it very closely initially but I can't re-create it now.  I'm new to svelte too, must have been my error.
