### ISSUE TITLE
Can't import Felte using esbuild

### ISSUE THREAD

**Issue by jaredcwhite** [pablo-abc/felte#128]
### Describe the bug

Install esbuild (latest version is 0.14.36).

Create a file `testing.js`:

```js
import '@felte/element/felte-form';
```

Then try to compile with esbuild, for example:

```
node_modules/esbuild/bin/esbuild --bundle testing.js
```

It outputs the following error:

```
✘ [ERROR] Could not resolve "@felte/element/felte-form"

    testing.js:1:7:
      1 │ import '@felte/element/felte-form';
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Importing the directory "./felte-form" is not supported:

    ../node_modules/@felte/element/package.json:38:20:
      38 │     "./felte-form": "./felte-form",
```

Some of the other Felte packages have similar issues.

### Which package/s are you using?

@felte/element (VanillaJS through custom elements), @felte/reporter-element

### Environment

- OS: macOS 12.3
- Browser:
- Version:

**Comment by pablo-abc** [comment]
Thanks for the issue! Can you try the latest versions? `@felte/element@0.4.3` and `@felte/reporter-element@0.3.2`.

I had defined incorrectly the "exports" field on `package.json`. I had only tried this with Vite and Rollup and it seems they both don't care about it (or fix it).

**Comment by jaredcwhite** [comment]
That did the trick! Thanks for the quick turnaround @pablo-abc :+1:
