### ISSUE TITLE
Can't install validators via pnpm

### ISSUE THREAD

**Issue by alex-way** [pablo-abc/felte#130]
### Describe the bug

When installing any of the following packages I get an error which prevents the packages being installed. This isn't happening with any other package to must be localised to felte.

```
EPERM  EPERM: operation not permitted, copyfile 'C:\Users\WayA\.pnpm-store\v3\files\29\4324b67c264be431302ecd00b302ae033132aa3233377e001fc1347c8a245bf8f97bf867e160639e313d3c7606258e87dd495d7bcb6ddcb2b2b1dc8101cf39-exec' -> 'C:\code\lyra-donations-platform\node_modules\.pnpm\@felte+validator-superstruct@1.0.5_superstruct@0.15.4\node_modules\@felte\_tmp_2640_ddc853a480ae5a57def68d01453f40eb\.turbo\turbo-test:ci.log'
```

### Which package/s are you using?

@felte/validator-yup, @felte/validator-zod, @felte/validator-superstruct

### Environment

- OS: Windows 10
- Browser: N/A
- Version: N/A

### To reproduce

Run `pnpm add @felte/validator-superstruct`

**Comment by pablo-abc** [comment]
I don't have a Windows machine to test on. Is this only happening with `ppm`? Do other package managers work as expected? This might give me a good starting point to check this.

**Comment by alex-way** [comment]
I've just installed one of the packages successfully via `npm install @felte/validator-superstruct` .

 I also did a complete nuke of my node_modules both in my repository and also globally but it seems that the issue is still present.

Happy to run any commands if you need further info and thanks for getting back to me so quickly 😄

**Comment by pablo-abc** [comment]
Can you try the latest patch I published? I saw the error happens when trying to copy a file that does not need to be published, so I just excluded it.

**Comment by alex-way** [comment]
FIxed! Happy for this one to be closed!

**Comment by pablo-abc** [comment]
Perfect, then! I'll be closing this. Thanks for submitting your issue!
