### ISSUE TITLE
Pass all stores (e.g. isDirty) to extenders

### ISSUE THREAD

**Issue by pz-mxu** [pablo-abc/felte#133]
Extenders can currently only access some of the stores (data, touched, errors). 

To use extenders for all kinds of extensions, it would be nice to have access to all stores.

In addition to that, having access to a function "submit", that triggers a submit, would be great, analog to "validate" that triggers a validate.

**Comment by pablo-abc** [comment]
This sounds perfectly reasonable! What kind of use cases are you expecting these stores to be used for? 

For the submit action, I'm guessing making `createSubmitHandler` should be enough for your use-case?

**Comment by pz-mxu** [comment]
I want to submit the form periodically after changes. The timer is started from the extender and because of that I would like to trigger submit from there. Since neither "handleSubmit" nor "createSubmitHandler" are available inside the extender, as far as I saw, I am currently using "handleSubmit" returned by "createForm" in my extender, that has to be defined in the same scope for this to work. It would be easier, if "handleSubmit" or "createSubmitHandler" were available in the extender.

Since "isDirty" is reset after a successful submit, I use that flag to decide if I have to submit the form or not. Extenders are called a couple of times, and I can avoid double submit that way.

**Comment by pablo-abc** [comment]
Hey, @pz-mxu . Starting on 1.2.0, extenders will receive all stores + `handleSubmit` and `createSubmitHandler`!
