### ISSUE TITLE
Default submit handler gets html, not json from Sveltekit page endpoints

### ISSUE THREAD

**Issue by janwicher** [pablo-abc/felte#137]
### Describe the bug

With Sveltekit _page endpoints_, the default submit handler receives HTML from the page (ie: the form itself) and not json from the endpoint (ie: the response on the submit).

Page endpoints have the page and the endpoint on the same URL. You will need to include an `Accept: application/json` header to get JSON from the endpoint rather than HTML from the page.

### Which package/s are you using?

felte (Svelte)

### Environment

- OS: Windows 11
- Browser: Chrome
- Version: 101.0.4951.54

### To reproduce

Page `login.svelte` with a form:
```js
<script lang="ts">
  import { createForm } from 'felte';

  const { form } = createForm({
    onSuccess(response, context) { console.log(response.status) } // <-- logs 200 from page, but want 401 from endpoint
  })
</script>

<form use:form method="post">
  <button type="submit">Go</button>
</form>
```

Endpoint `login.ts` with a request handler:
```js
import type { RequestHandler } from '@sveltejs/kit'

export const post: RequestHandler = async ({ request }) => {
  return {
    status: 401 // <-- return 401 Not Authorized
  }
}
```
The page and the endpoint have the same url (`/login`). An Accept header should distinguish between page or endpoint.

### Additional context

**Sveltekit page endpoints** ([docs](https://kit.svelte.dev/docs/routing#endpoints-page-endpoints)):
> If an endpoint has the same filename as a page (except for the extension), the page gets its props from the endpoint — via fetch during client-side navigation, or via direct function call during SSR.
> Because the page and route have the same URL, you will need to include an accept: application/json header to get JSON from the endpoint rather than HTML from the page.

**Workaround**:
> You can also get the raw data by appending /__data.json to the URL, e.g. /items/[id]/__data.json.

**Comment by janwicher** [comment]
Here is what the workaround looks like, with the `/__data.json` suffix:
```js
<script lang="ts">
  import { createForm } from 'felte';

  const { form } = createForm({
    onError: async (error) => {
      const body = await error.response.json();
      // shape response body into errors
    }
  });
</script>

<form use:form method="post" action="/users/login/__data.json">
  <button type="submit">Go</button>
</form>
```

**Comment by pablo-abc** [comment]
This might be on SvelteKit as far as I understand! Although I'm not sure how it handles server endpoints and components called the same?

I've always made a point of adding `.json` to my server endpoints when using SvelteKit. E.g. Having a `/users/login.svelte` for the page and a `/users/login.json.js` for the API endpoint. But if this is something SvelteKit should support now, I'll check if there's something I can do on my end (maybe missing headers?).

**Comment by pablo-abc** [comment]
Can you test the latest version? Just pushed a patch that sends the headers appropriately. Feel free to close this if it works as expected.

**Comment by janwicher** [comment]
I just tested with version `felte@1.2.2` and the request works OK now.

But the page is not getting its props from the response. With Sveltekit page endpoints (ie: page and endpoint with same name), this is done automatically. I can do it manually in `onSuccess` though:
```js
let msg: string;

const { form } = createForm({
  async onSuccess(response, context) {
    msg = (await response.json()).msg;
  }
})
```
It works with a workaround, but I think it doesnt fully support Sveltekit page endpoints. Want to keep this one open to look at that? If there are no plans (I'm not planning myself), then I can close.

**Comment by pablo-abc** [comment]
Sorry for the delay, @janwicher. But yeah, there's no plans for that currently. Page endpoints don't work because the request is being done with JS, not the native submit event. This API was thought before SvelteKit's form handling.

This is something I'll give thought to, since the way I see it might require an API change (so maybe for Felte v2?). But maybe there's a way to handle it without introducing breaking changes. Anyway, it's okay to keep this closed. I'll just keep a note about this.

**Comment by dlamon1** [comment]
With Sveltekit v1.0.0, it seems that getting any usable error message back from the server is....very close to impossible. Is there plans for further development with the latest update? I took a look at the docs myself, but, I am not a smart person.

**Comment by canastro** [comment]
@dlamon1 try this:

```ts

  import { deserialize } from '$app/forms';

	const { form, errors, touched, isSubmitting } = createForm({
		async onSuccess(response, context) {
			const res = await response.text();

			console.log({ res: deserialize(res) });
		},
	});
```
