### ISSUE TITLE
Minor Feature Request

### ISSUE THREAD

**Issue by abhijit-kar** [pablo-abc/felte#14]
Smooth scroll to the error field, instead of an abrupt one.

It's just a nice to have, not entirely necessary, but will fit well with wherever I use [svelte-scrollto](https://www.npmjs.com/package/svelte-scrollto).

**Comment by pablo-abc** [comment]
I don't think this should be a default behaviour, but allowing to pass options to the `scrollTo` method being called can be done. I imagine you would need to add a polyfill for it to work in Safari.

 I'll work on this as soon as I can.

**Comment by pablo-abc** [comment]
So it seems it is not as simple as I might have thought. `focus()` doesn't accept scroll options unlike scrollTo, and adding functionality to scrollTo with smooth scroll, wait for the scroll to end and then focus the input element would add unnecessary complexity for the default of not having smooth scroll at all.

I think this brings me to an issue I already had, the API for making/customizing extenders is not that simple yet and it's something I'm working on actively right now. For now what I can think off for solving this is for you to use a higher order function on the reporter to "override" the [`onSubmitError`](https://felte.dev/docs#extending-felte) function returned by the reporter.

**Comment by abhijit-kar** [comment]
Hey @pablo-abc,

I figured it out, adding the following css made it scroll smooth!!

```
html {
    scroll-behavior: smooth;
}
```
