### ISSUE TITLE
Remove empty strings

### ISSUE THREAD

**Issue by jcalfee** [pablo-abc/felte#144]
**Is your feature request related to a problem? Please describe.**

Is there a way to remove empty strings in the form's submitted values?

**Describe alternatives you've considered**

Recursively remove them, this is a nested stricture.

**Additional context**
```svelte
<script>
  const form = createForm({
    onSubmit: (values) => {
      console.log('submit =', JSON.stringify(values, null, 2))
    }
  })
</script>

<form use:f.form>
  <input name="name" />
  <button type="submit">submit</button>
</form>
```
No-input submit outputs:
```js
submit = {
  "name": ""
}
```
Preferred:
```js
submit = {}
```

**Comment by pablo-abc** [comment]
This is to be expected, since the fields actually have an empty string as a value. If you want to completely remove it as you request, you could use [transformations](https://felte.dev/docs/svelte/transformations).

**Comment by jcalfee** [comment]
Good thinking .. thank you
