### ISSUE TITLE
createField onInput value gets converted from number to string

### ISSUE THREAD

**Issue by tylkomat** [pablo-abc/felte#156]
### Describe the bug

I use `createField` in my custom component and set the value, which is a number, via `onInput`. The value inside of `$data` for that field is a string.

### Which package/s are you using?

felte (Svelte)

### Environment

- OS: Windows 10
- Browser: Firefox
- Version: felte@1.2.2

### To reproduce

Click on + or - and watch the console

### Small reproduction example

https://svelte.dev/repl/b0b834e9ccbb414981bfbfe4c6ac43d0?version=3.49.0

**Comment by pablo-abc** [comment]
This happens because, in order for your "custom input" to actually be seen as an input (e.g. so it can be taken from the form's `FormData`), Felte creates a `<input type="hidden">` which holds the value. This will always be a string since said input element is where Felte takes the value from.

**Comment by tylkomat** [comment]
I see. Thanks. I went with the `bind:value` solution.
