### ISSUE TITLE
multipart/form-data should not contain content-type header

### ISSUE THREAD

**Issue by lulucas** [pablo-abc/felte#165]
### Describe the bug

If post 'multipart/form-data' form by fetch, it should not contain content-type header, the boundary will be missing.

Related issues

https://stackoverflow.com/questions/39280438/fetch-missing-boundary-in-multipart-form-data-post

### Which package/s are you using?

felte (Svelte)

### Environment

- OS: windows
- Browser: edge
- Version: [felte@1.2.2]

**Comment by pablo-abc** [comment]
Sorry for the delay! This should be fixed now on the latest release. If you can give it a try, that'd be great!
