### ISSUE TITLE
types from `svelte/store` is required even for react project

### ISSUE THREAD

**Issue by stregouet** [pablo-abc/felte#171]
### Describe the bug

Hi,
first thanks for providing such a good lib! I'm already using it with a svelte project and it works nicely :)

Now I want to also use felte in a react + ts project but I end up with the following typescript error:

```
node_modules/@felte/common/dist/types/types-27598f9f.d.ts:1:36 - error TS2307: Cannot find module 'svelte/store' or its corresponding type declarations.

1 import { Readable, Writable } from 'svelte/store';
``` 

and actually I didn't install `svelte` (no need on react project). I found  a store definition in `@felte/react` (@felte/react/dist/types/stores.d.ts) which is really similar so I add a `paths` entry in tsconfig.json 

```
  ...
          "paths": {
          "svelte/store": ["./node_modules/@felte/react/dist/types/stores"],
        },
  ...
```

but I get another error about missing `Readable` interface.

What do you think about adding this interface in `@felte/react`? (of course I can write and submit a pull request if you find it's valuable) Or is there another workaround to fix my issue? 

### Which package/s are you using?

@felte/react (ReactJS), @felte/common

### Environment

- OS: linux
- Browser: firefox
- Version: typescript@4.7.4, @felte/common@1.1.2 @felte/react@1.2.3

**Comment by pablo-abc** [comment]
You're right! This is some tech debt from when Felte was exclusively a Svelte library. For what it's worth, the imports are just types so nothing extra is added to the bundle from Svelte

Replaced the imports from svelte/store to our own types. Starting on the latest version svelte is no longer needed as a dev dependency. Feel free to give it a try and close this if it works for you!

**Comment by pablo-abc** [comment]
Closing this since there was no further comments!
