### ISSUE TITLE
initialValues doesn't update DOM correctly for <select> elements with <option value="...">

### ISSUE THREAD

**Issue by level2-alejandro** [pablo-abc/felte#174]
### Describe the bug

When using a `<select>` element for a form field and using the `value=""` attribute on its <option> elements, e.g. for objects with IDs, initialValues does not function properly, and the selected option on the DOM is always the first option. (The value is correct in the underlying form data.)

### Which package/s are you using?

felte (Svelte), @felte/reporter-svelte, @felte/validator-zod

### Environment

- OS: Windows
- Browser: Chrome
- Version: felte@1.2.3, @felte/reporter-svelte@1.1.3, @felte/validator-zod@1.0.11

### To reproduce

- Create an array of objects with ID and name properties to serve as the options.
- Create a form with an initial value matching an ID of one of the options.
- Create a `<select>` element and set its name to the field we set the initial value for.
- Create `<option>` elements for all our objects, setting their value attribute to their ID and their content to the name.
- Observe that while the value of the dropdown ID is correctly set in the form data store, the dropdown in DOM does not reflect this and always shows the first value.

### Small reproduction example

https://codesandbox.io/s/felte-select-initialvalues-forked-4u1ssi?file=/App.svelte

**Comment by pablo-abc** [comment]
Hey, @level2-alejandro . I believe this is happening because the "value" of a `<select>` is always a string in the underlying DOM element. We're not casting to anything in the background. Changing the `ids` and the value of `dropdown` to a string solves your issue.

I'll leave this open and see to making what you're trying to do possible, though!

**Comment by pablo-abc** [comment]
Hey, @level2-alejandro. This should be working correctly as you expected on 1.2.5! Give it a try
