### ISSUE TITLE
Dynamic Forms not working in `@felte/solid`

### ISSUE THREAD

**Issue by biowaffeln** [pablo-abc/felte#175]
### Describe the bug

Dynamic fields don't seem to be working properly in `@felte/solid`. For example, if I dynamically remove and add an input field, the value still exists when I submit it (see Stackblitz example below).

### Which package/s are you using?

@felte/solid (SolidJS)

### Environment

- Browser: Chrome
- Version: @solid/felte@1.2.3

### Small reproduction example

https://stackblitz.com/edit/vitejs-vite-vveu7v?file=src/App.tsx

**Comment by pablo-abc** [comment]
Just pushed an update that should have fixed this. Can you try v1.2.4?

**Comment by biowaffeln** [comment]
Just tried it out, looks good. Thank you!
