### ISSUE TITLE
[Feature Request] - HMR Store with Local Storage Support

### ISSUE THREAD

**Issue by abhijit-kar** [pablo-abc/felte#18]
Hey @pablo-abc,

I have a feature request, HMR & Local Storage:

1. With HMR, working with forms in Vite will be crazy fast.
1. With Local Storage support, the form data will become impervious to data loss in case of page refresh.

Is it prudent to add HMR Store & Local Storage support to felte's stores?

I took the following HMR Safe Store code from Vite init.

```javascript
// Customized HMR-safe stores
// Based off https://github.com/svitejs/svite/blob/ddec6b9/packages/playground/hmr/src/stores/hmr-stores.js
import { writable } from "svelte/store";

/**
 * @type { Record<string, import('svelte/store').Writable<any>> }
 */
let stores = {};

/**
 * @template T
 * @param { string } id
 * @param { T } initialValue
 * @returns { import('svelte/store').Writable<T> }
 */
export function getStore(id, initialValue) {
	return stores[id] || (stores[id] = writable(initialValue));
}

// preserve the store across HMR updates
if (import.meta.hot) {
	if (import.meta.hot.data.stores) {
		stores = import.meta.hot.data.stores;
	}
	import.meta.hot.accept();
	import.meta.hot.dispose(() => {
		import.meta.hot.data.stores = stores;
	});
}
```
P.S. I won't mind a workaround instead.

**Comment by pablo-abc** [comment]
Would this cause any issues in other environments apart from Vite? Like the default plain Svelte + Rollup template? 

If there won't be any compatibility issues, this sounds like a nice addition.

**Comment by abhijit-kar** [comment]
Perhaps It can be conditionally enabled, if vite env is detected, via import.meta!

Or maybe we can have switchable stores, just like reporter & validators.

**Comment by pablo-abc** [comment]
I feel this could also be done via the existing "extenders" API. Since you have access to the stores there. Not necessarily a HMR feature yet (I'd like to experiment with that before) but more of a localStorage persistence plugin.

**Comment by abhijit-kar** [comment]
Will check it out. 🙃

**Comment by pablo-abc** [comment]
I've been quite busy these past few days, not much time to check on this. But I can also get around to do something with this idea during the next few days.

**Comment by abhijit-kar** [comment]
Hey @pablo-abc,

Please take your time. I've been busy with an interview, so I couldn't try out what you commented, and couldn't write the blog post I mentioned.

**Comment by hmaesta** [comment]
Just don't forget to add a param to specify that certain inputs don't should be saved on localstorage, like credit card data.

**Comment by pablo-abc** [comment]
I've uploade a rough version of how this might work in [`@felte/extender-persist`](https://www.npmjs.com/package/@felte/extender-persist). As noted by @hmaesta , you can choose to ignore certain fields (I'm not sure if ignoring `type=password` fields by default might be desired?)

**Comment by pablo-abc** [comment]
I'm closing this since there was no further concerns. If anything else arises feel free to open a new issue.
