### ISSUE TITLE
Proposal a way to handle formAction

### ISSUE THREAD

**Issue by AndreasHald** [pablo-abc/felte#2]
Very nice job on felte! it's such an interesting form framework, and i love the approach of essentially defining everything from the HTML. I was thinking about how we usually handle the same form being used for multiple purposes in plain html, and it's done using the ```formAction``` [attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/submit#formaction) on the submit input, that way you can have several different submit buttons posting the form to different places.

I was thinking felte would be perfect for implementing a way to do this as well.

We could add another property ```data-felte-set-on-submit``` to input fields, that would only include the value of that field, if that corresponding submit button was used to submit the form here's an example of how the html could look:
https://svelte.dev/repl/099c65345fe043a79774c480d3b44070?version=3.34.0

The onSubmit function could then handle different submit functions based on which property was used to submit the from.

How do you feel about something like this? if it's something you think would be interesting i'd be happy to give a PR a shot.

**Comment by pablo-abc** [comment]
I feel I do understand your use case, but I'm not sure I understand how would you expect the API itself to look like.

How would, e.g., this line be reflected in the `createForm` config object?

```html
<input data-felte-set-on-submit type="submit" name="action_1" value="action_1">
```

Would it pass an additional value to the `onSubmit` function letting the developer know which button was pressed? Or would it need a function to be defined in the config object itself? e.g.:

```javascript
const { form } = createForm({
  action_1: () => /* ... */,
});
```

The latter seems like it would make the TypeScript typing quite complicated, tho.

I do understand that an HTML5 submit button [can override the action used by the form using the `formaction` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/submit#htmlattrdefformaction), so having something like this would be useful. I'm just not sure on to best approach how the final API should look like for something like this.

What would you say would be the advantages of Felte itself handling something like this over using a `<button on:click={action}>`. Right now I see Felte handling it and doing it with a button click handler requiring about the same amount of work by the developer. But maybe there's something I'm missing here.

**Comment by AndreasHald** [comment]
Yeah the main purpose would be to have a single HTML form that could be used for multiple purposes, while the HTML is the same whether or not JS is enabled on the client.

Both of the cases you mention would be fine by me, it was the first i was thinking about, and you may be right about the typescript complexity of the second.

You could have something like this:

```js
const { form } = createForm({
  onSubmit: ({type, ...opts}) => type === 'action_1' ? performAction1(opts) : performAction2(opts),
});
```

```html
<form use:form>
   /*... rest of form elements */
   <input data-felte-set-on-submit formaction="/action_1" type="submit" name="type" value="action_1">
   <input data-felte-set-on-submit formaction="/action_2" type="submit" name="type" value="action_2">
<form>
```

This way if the client has JS, you can enrich the experience, but this would be perfectly valid with JS disabled.

**Comment by pablo-abc** [comment]
Just as a minor update, I've been tinkering with the idea of returning a helper function that could override the default submit handler.

So a possible API could be looking like:

```html
<script>
  const { form, createSubmitHandler } = createForm(/*...*/);

  // First arg with same signature as `onSubmit`
  const altOnSubmit = createSubmitHandler((values) => {
    /* ... */
  })
</script>

<form use:form>
  <!-- ... -->
  <button type="button" on:click={altOnSubmit}>Alt Submit</button>
</form>
```

This way the createForm config API would remain simple while still providing a more advanced use case with the use of helper functions.

**Comment by AndreasHald** [comment]
This would also be a very interesting solution, however in order for the same HTML to work both with & without js, all button types would need to be ```submit``` how would that work? would you then need to stop event propagation on the second button in order for it not to submit the main form submitHandler

```svelte
<script>
  const { form, createSubmitHandler } = createForm(/*...*/);

  // First arg with same signature as `onSubmit`
  const altOnSubmit = createSubmitHandler((values) => {
    /* ... */
  })
</script>

<form use:form method="POST" action="handle_action_1">
  <!-- ... -->
  <button type="submit">Action 1</button>
  <button type="submit" action="handle_action_2" on:click|stopPropagation={altOnSubmit}>Action 2</button>
</form>
```

**Comment by pablo-abc** [comment]
I've gone ahead and added this to 0.4.10, I've also [updated the docs](https://felte.dev/docs#createsubmithandler) with an example on its usage. The final version of this function can override `onSubmit`, `validate` and `onError`.

Feel free to test if it solves your use case!

**Comment by pablo-abc** [comment]
I'll go ahead and close this now. But it can be reopened if there's anything missing.
