### ISSUE TITLE
Input empty when added to the DOM

### ISSUE THREAD

**Issue by sproott** [pablo-abc/felte#203]
### Describe the bug

When there's a hideable input on the page and it gets removed from the DOM and then added again, it doesn't get its value assigned from the `$data` store. Instead, it stays empty. 

Note that I've used `data-felte-keep-on-remove` to keep the data in the store after removing the input. The data is there, just the input doesn't get the value.

### Which package/s are you using?

felte (Svelte)

### Environment

- OS: Linux
- Browser: Firefox
- Version: felte@1.2.6

### To reproduce

1. Have an input that's hideable, for example by a checkbox and has the `data-felte-keep-on-remove` attribute
1. Enter some text
2. Hide the input
3. Show it again
4. The input is empty even though it should contain the text you entered

### Small reproduction example

https://codesandbox.io/s/felte-show-input-bug-vfs7qh

**Comment by pablo-abc** [comment]
Hey! This has been fixed on #210 (so `felte@1.2.7`)

I had not noticed this was reported before #208

I'm closing this but feel free to reopen if it's not working as expected!
