### ISSUE TITLE
Initial value not set in dynamic forms (felte - Svelte)

### ISSUE THREAD

**Issue by AgarwalPragy** [pablo-abc/felte#208]
### Describe the bug

In the example on dynamic forms mentioned in the doc, the initial value of textarea `name='bio'` does not get set.

Note that `data-felte-keep-on-remove` is enabled and works as expected - the `$data` store shows that the `bio` field is kept even after `hasBio` is `false`.

### Issue

When `hasBio` is toggled back to `true`, the textarea doesn't get populated with the value

### Expected behavior
When `hasBio` is toggled back to `true`, the textarea must get populated with the value of `$data.bio`

### Which package/s are you using?

felte (Svelte)

### Environment

- OS: macOS Ventura (13.1)
- Browser: Version 108.0.5359.124 (Official Build) (arm64)
- Version: felte@1.2.6,  @felte/core@1.3.6

### To reproduce

```svelte
<script>
  import { createForm } from 'felte';

  const { form, data } = createForm({
    initialValues: {
      username: "user", 
      hasBio: true, 
      bio: "biodata"
    }
  });

  let hasBio = true;
</script>

<pre>{JSON.stringify($data, null, 2)}</pre>
<form use:form>
  <fieldset data-felte-keep-on-remove>
    <div>
      <input name="username">
    </div>
    <div>
      <input type="checkbox" name="hasBio" bind:checked={hasBio}>
    </div>
    {#if hasBio}
      <div>
        <textarea name="bio" />   
      </div>
    {/if}
  </fieldset>
</form>
```

### Small reproduction example

https://svelte.dev/repl/0e866d6f96bd4e08a64422404ff9a20e

**Comment by gl-aagostino** [comment]
You could resolve this with `bind:value={$data.fieldname}` but this introduces another problem: when you use field name with `.` such as `profile.name` it serializes into `profile.name: "value"` instead of `profile: { name: "value" }`
