### ISSUE TITLE
[question] is it possible to validate the field after user starts typing?

### ISSUE THREAD

**Issue by zhyph** [pablo-abc/felte#209]
Hey,
I'm so far enjoying the package.

I've noticed that the field wouldn't be validated until it was touched (blur), and then it would dynamically update depending on whether it was valid or not.
This was the expected outcome based on what I saw, and it should be this way.
But how could I validate a field as soon as the user types something into it? Is there something in felte that I'm missing, or would this one be more of a handy work, rather than waiting for the field blur or form submit?

Thanks for any clarification, and again, loving the package.

**Comment by pablo-abc** [comment]
Hey! Felte is always validating under the hood, it just does not _display_ the errors until the the field has been interacted with ("touched").

If you want to show the error since the user starts typing, you can call `setTouched('field-name', true)` as soon as the user starts typing to trigger this.

**Comment by zhyph** [comment]
> Hey! Felte is always validating under the hood, it just does not _display_ the errors until the the field has been interacted with ("touched").
> 
> If you want to show the error since the user starts typing, you can call `setTouched('field-name', true)` as soon as the user starts typing to trigger this.

I thought about doing this, just wondered if there was more direct way of doing it.
I wanted to avoid the multiple calls to `setTouched`, but if this is really the only option, thank you for your help.

**Comment by pablo-abc** [comment]
Yeah, generally this behaviour is what (after some discussion on previous issues) seems to be preferred.

May I ask what is your use case for this?

**Comment by zhyph** [comment]
> Yeah, generally this behaviour is what (after some discussion on previous issues) seems to be preferred.
Got it.
> May I ask what is your use case for this?
Basically something similar to what react-form-hook does, whenever the user starts typing, it validates the field. The only difference is that using `setTouched` makes the field validate from the go (starting with errors with required fields), but what I needed is for the field to start validating only after the user typed something, without ever clicking out the field.
I think I can do that easily using some extra logic, so no biggie
