### ISSUE TITLE
Reporter DOM should not require the id to be set.

### ISSUE THREAD

**Issue by tacone** [pablo-abc/felte#21]
Currently this works:

```html
<input type="text" name="email" id="email" />
<div data-felte-reporter-dom-for="email" aria-live="polite" />
```
This does not:

```html
<input type="text" name="email" id="email" />
<div data-felte-reporter-dom-for="email" aria-live="polite" />
```
Here's the relevant code of Reporter DOM:

```typescript
  if (!target.name || !target.id) return;
  const validationMessage = target.dataset.felteValidationMessage;
  const reporterElement = document.querySelector(
    `[data-felte-reporter-dom-for=${target.id}]`
  );
```
I think we should not need to assign ids to every form element.

**Comment by pablo-abc** [comment]
You are totally right. It's more intuitive for `data-felte-reporter-dom-for` to behave just like your form controls' `name` attribute. (This is how `@felte/reporter-tippy` works as well). I'll make this change and update it as a minor version.

**Comment by pablo-abc** [comment]
You may find the fix for this already in @felte/reporter-dom@0.2.0, if you feel this solves this issue feel free to close it!

**Comment by tacone** [comment]
Awesome.

Works well. I tested it with this snippet:

```svelte
	<div data-felte-reporter-dom-for="email" />
```
I like Felte a lot, thank you for it.
