### ISSUE TITLE
Error Function called outside component initialization on Homepage Sandbox

### ISSUE THREAD

**Issue by LarsHadidi** [pablo-abc/felte#259]
### Describe the bug

Embedded Sandbox with Svelte Example on Landing Page is showing error

### Which package/s are you using?

felte (Svelte)

### Environment

- OS: Windows 11
- Browser: Chrome 116.0.5845.96 
- Version: latest

### To reproduce

Go to https://felte.dev/

Load Example **Using Svelte**

**Comment by pablo-abc** [comment]
Was breaking my head with this but it seems to be an issue with CodeSandbox and later versions of Svelte?

Downgraded to a previous version and it seems to work now!

**Comment by LarsHadidi** [comment]
Hello, oh yea, fun with technology, eh. I hope it didn't take too much of your energy, it's just the 1st impression on the page and Felte is such an awesome work, it should definetely show off. Each time I work with the API, I discover more supportive stuff that just makes my development smoother. Fantastic Lib, really !!! :-)
Just checked with my Chrome Browser: _Error Function called outside component initialization_ :-P
