### ISSUE TITLE
Validation of dynamically added input type="number" does not work if input has not been touched

### ISSUE THREAD

**Issue by zeronius** [pablo-abc/felte#260]
### Describe the bug

Hi, I develop application with Felte used mainly for validations but I face an issue:

1. I've got a form with inputs that are conditionally rendered with some delay (e.g. after some data are loaded).
2. Some of those inputs are `<input type="number">`.
3. There are some custom validations of those inputs, e.g. that inputs are required. Those validations are bound via `createForm({... validate: (values) => .... })
4. Validation error messages are rendered via `ValidationMessage` component.
5. On click on button I run form validation via `validate` method (`const { validate } = createForm(...`)
6. When user does **not touch required inputs and clicks on submit button, then errors are shown only for `<input type="text">` but not for `<input type="number">`**. Also number input does not contain attribute `aria-invalid="true"` which is usually added for invalid inputs as well as the related error is not in `$errors` store.
7. When user touches the input (focuses it and blurs), then errors are properly shown.

**See the demonstration of the issue**: https://svelte.dev/repl/bf1932ca8439445eb76a40c2c4a87390?version=3.59.2 .

This seems as bug for me. I think that errors should be shown also for number inputs.

Is there a workaround for it such as programmatically re-initialize the form in Felte?
Thank you. 

### Which package/s are you using?

felte (Svelte), @felte/reporter-svelte

### Environment

- OS: Win11
- Browser: Chrome 116.0.5845.97 (64 bit); Firefox 116.0.3 (64 bit)
- Version:  felte: 1.2.11, @felte/reporter-svelte: 1.1.10, svelte: 3.59.2

### Small reproduction example

https://svelte.dev/repl/bf1932ca8439445eb76a40c2c4a87390?version=3.59.2

**Comment by pablo-abc** [comment]
This was definitely a bug! Thanks for pointing it out. A fix has been published 😄
