### ISSUE TITLE
@felte/reporter-solid v 1.2.9 kills solid start

### ISSUE THREAD

**Issue by timothyallan** [pablo-abc/felte#266]
### Describe the bug

Downgrading to 1.2.8 fixes things, but as soon as I update `@felte/reporter-solid` to 1.2.9 I get:

```
An unhandled error occured: TypeError: __vite_ssr_import_1__.template is not a function
at /dev/project/node_modules/@felte/reporter-solid/src/stores.ts:35:29
```

As soon as I run `npm run dev` with a solid start project.

### Which package/s are you using?

@felte/reporter-solid

### Environment

- OS: Any
- Browser: Any
- Version: 1.2.9

### To reproduce

Create a new solid start project named my-app via
`npm init solid@latest`
`cd my-app`
`npm install --save @felte/reporter-solid`

in `root.tsx`, put `import { reporter } from "@felte/reporter-solid";`

run it with `npm run dev`

Boom.

**Comment by jchatard** [comment]
I confirm the same behavior.

**Comment by pablo-abc** [comment]
Thanks for reporting! Will look into this
