### ISSUE TITLE
initialValues does not work with <select>

### ISSUE THREAD

**Issue by umanghome** [pablo-abc/felte#27]
Reproduction of the issue: https://codesandbox.io/s/felte-select-initialvalues-932ld?file=/App.svelte

**Comment by umanghome** [comment]
This seems to be the culprit. It does an early return for `<select>` elements: https://github.com/pablo-abc/felte/blob/f5bf1c6117481b1f042081892194780da5f200c2/packages/common/src/utils/domUtils.ts#L137

**Comment by half2me** [comment]
I've just run into this issue too.

**Comment by pablo-abc** [comment]
Fix released on felte@0.7.2, thanks a lot for the PR @umanghome! I've added you as a contributor to the README
