### ISSUE TITLE
setData does not update inputs' value

### ISSUE THREAD

**Issue by aryzing** [pablo-abc/felte#271]
### Describe the bug

Using `setData` does not update an input's value. For example, given an input with `name="color"`, calling `setData({color: "blue"})` will indeed update the `data` store, but the input's value will remain unchanged.

**However**, calling `setFields()` on any field will update all inputs with the values of the `data` store. Example:

```ts
setData({color: "blue"}) // nothing happens. name="color" input's value is unchanged
setFields({foo: "bar"}) // will update both name="foo" and name="color" inputs' values
```

### Which package/s are you using?

felte (Svelte)

### Environment

- OS: Linux
- Browser: Chrome
- Version: 118

### To reproduce

[See reproduction](https://svelte.dev/repl/ce59ea59c33d4124aa38dd6a6112ffb6?version=4.2.1)

### Small reproduction example

https://svelte.dev/repl/ce59ea59c33d4124aa38dd6a6112ffb6?version=4.2.1

**Comment by pablo-abc** [comment]
The idea was to have methods that are completely decoupled from the DOM. E.g. if you wanted to keep some extra data that is not represented by fields in HTML. `setFields` will probably be the default one to reach for for most cases. I'll see to make it more prominent in the documentation.
