### ISSUE TITLE
Simplify return type of `createForm`

### ISSUE THREAD

**Issue by aryzing** [pablo-abc/felte#275]
**Is your feature request related to a problem? Please describe.**
Simplify return type of `createForm`

**Describe the solution you'd like**
To have a single generic type for the return type of `createForm`. It would allow passing the form between components in a typesafe way.

At present, what would be the type of a property on a component that accepts a `createForm()` value?

**Describe alternatives you've considered**
Using `any`.

**Additional context**
Using Solidjs

**Comment by pablo-abc** [comment]
Catching up a bit. Currently I don't export any types for it but is it generic enough if you do something such as this?

```typescript
export type FelteForm = ReturnType<typeof createForm>;
```
