### ISSUE TITLE
Array lists don't work with Solid.js

### ISSUE THREAD

**Issue by aryzing** [pablo-abc/felte#276]
### Describe the bug

When the form state contains an array of fields, they will not render with Solid.js,

```tsx
<>
        {/* None of these fields will render */}
        <For each={data().someFields}>
          {(_field, i) => <input name={`someFields.${i()}.value`} />}
        </For>
</>
```

### Which package/s are you using?

@felte/solid (SolidJS)

### Environment

- OS: Ubuntu 22.04 LTS
- Browser: Brave v1.59.120
- Version: @felte/solid 1.2.11

### To reproduce

https://stackblitz.com/edit/solidjs-templates-ezxdwm?file=src%2FApp.tsx

### Small reproduction example

https://stackblitz.com/edit/solidjs-templates-ezxdwm?file=src%2FApp.tsx

**Comment by oddcelot** [comment]
Just tried Felte, today and isn't the value accessed this way? Seems to work in the blitz at least 🤷‍♂️

```diff
<>
        {/* None of these fields will render */}
-       <For each={data().someFields}>
+       <For each={data("someFields")}>
          {(_field, i) => <input name={`someFields.${i()}.value`} />}
        </For>
</>
```

**Comment by aryzing** [comment]
Thanks @oddcelot, at this point I've moved on from felte, so I'll close the issue if it works for you.
