### ISSUE TITLE
I can't use PUT on form method

### ISSUE THREAD

**Issue by jmaister** [pablo-abc/felte#298]
### Describe the bug

I am creating a form component that would allow to create new user or update.
For the form method, I do a ternary expression to select POST or PUT, depending on the action and it does not work.

The form method only allows "post", "get" or "dialog", which is odd only those ones.

![imagen](https://github.com/pablo-abc/felte/assets/374021/1b7665ed-06c9-4c73-9994-6cfe49c0d946)

![imagen](https://github.com/pablo-abc/felte/assets/374021/1d1adf81-8899-40c2-990a-343173fb3890)

![imagen](https://github.com/pablo-abc/felte/assets/374021/ee5ecba7-4372-45df-b543-b035bf060b21)

### Which package/s are you using?

@felte/solid (SolidJS)

### Environment

- OS: Windows 11
- Browser: Firefox / Chrome
- Version: "@felte/solid": "^1.2.13", "solid-js": "^1.8.17",

### To reproduce

Create a form, use "put" on the method.

**Comment by pablo-abc** [comment]
Hi! This is not due to Felte but to the [HTML specification](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#method). Those are the only methods supported by the `<form>` element. If another method is needed I'd usually go towards using an onSubmit function.
