### ISSUE TITLE
Feature request: Change generic constraint for `createForm`

### ISSUE THREAD

**Issue by nachtjasmin** [pablo-abc/felte#35]
## Current state

When providing an interface without the index signature (example below), the TypeScript compiler fails on `createForm` with the following error:

```
Type 'LoginRequest' does not satisfy the constraint 'Record<string, unknown>'.
  Index signature is missing in type 'LoginRequest'.
```

The `LoginRequest` itself looks like this.
```ts
export interface LoginRequest {
	email?: string;
	password?: string;
}
```

Code that throws the error:
```ts
const { form, data, errors } = createForm<LoginRequest>({
	onSubmit: (values) => console.log(values.email, values.password),
});
```

I could add the index accessor to the interface (they are generated based on our API), but this would reduce the type safety when using `keyof` or similar expressions in TypeScript.

## Expected state

The interface should be usable without compiler errors. *svelte-forms-lib* solves this by defining a default value for the type constraint, see https://github.com/tjinauyeung/svelte-forms-lib/blob/master/lib/index.d.ts#L6-L12.

**Comment by pablo-abc** [comment]
Giving a default value for the type does not seem to resolve the issue. What does it for _svelte-forms-lin_ is the fact that they're using `Record<string, any>` instead of `Record<string, unknown>`, I am not actually sure _why_ that happens but if you use `type LoginRequest = ...` instead of `interface` it does work without any issues.

I'll look more into this but I am open to switch this to `Record<string, any>` if I find no drawbacks to it.

**Comment by pablo-abc** [comment]
Adding to this, this behaviour seems to be intended by the TS compiler according to this: https://github.com/Microsoft/TypeScript/issues/15300#issuecomment-332366024

**Comment by nachtjasmin** [comment]
@pablo-abc Thanks for the hints! Converted the generated code so it uses `type LoginRequest = ...` now, everything works as expected! 
By the way, I really enjoy using felte so far, great work 👍

**Comment by pablo-abc** [comment]
That really means a lot! Thank you ☺️ I'm glad you're finding it useful!

In the end I'll change it to use `any`. Accepting interfaces can be useful and as long as you pass a type to the function it should be type safe. I think it's safe to assume that if someone doesn't specify a type they don't really care about type safety. 😅

**Comment by EirikFA** [comment]
It doesn't look like `Obj` was ever changed to `Record<string, any>` which sounds like a plausible solution. I currently cannot use a `type` as I import classes from a different package to use for validation. If changing the type of `Obj` does not have any drawbacks, it seems like the best option to allow interfaces or classes.
