### ISSUE TITLE
[Question] Best way to build progressive forms with felte?

### ISSUE THREAD

**Issue by benbender** [pablo-abc/felte#40]
As pictured in the default example of `sveltekit`, we have the perfect preconditions to build progressive forms with svelte which will work even without JS and progressively enhance with that. I quite like this feature and would like to use it with felte.

Problem is, that, if I add `method="post"` and `action="..."` to my felte-enhanced form, it will post the form with js loaded. It seems that felte doesn't do the `.preventDefault()`.

Ideally I would like to see that usecase supported first class in felte, but if that's out of/not your scope, I'm a bit unsure what the best way would be to achive it? As far as I could see, I could overwrite the `onSubmit-handler` but that seem to be a lot of boilerplate for the simple intercept...

**Comment by pablo-abc** [comment]
We do call `preventDefault` on submit. My initial thought was that if JS is loaded you'd handle your form submission with the `onSubmit` config parameter in `createForm`, but if JS is not loaded, the way you write a form with Felte is already compatible with an HTML form so it shouldn't prevent you from using `action` and `method`.

To be fair I haven't been up to date on how Svelte Kit is handling that right now, if there's a change we should do to make it compatible then I'd definitely be up to it.

**Comment by benbender** [comment]
Hmm, that's strange. I've had only a pure html-form for login and a submit-button... So I don't see any possible error on my end but will retest again. To be honest, I just assumed that felte doesn't do the `preventDefault` as my form redirected... Will test again!

**Comment by pablo-abc** [comment]
If you could make a repo or reproduction on CodeSandbox/Svelte's REPL that'd be great for me to check as well.

**Comment by benbender** [comment]
@pablo-abc Nevermind. Couldn't reproduce the problem myself and I'm unsure why... Same endpoint, same form... Sorry for the noise!
