### ISSUE TITLE
Disable felte handlers on custom components

### ISSUE THREAD

**Issue by greyivy** [pablo-abc/felte#41]
I have a custom component that wraps a textbox. On change, the value is transformed, then it should update felte's data store.

Because felte automatically binds the textbox's events/value, there is no way for me to transform this value.

Is there a way to disable felte's event handlers on a certain element and manually wire up setField?

**Edit:** a data attribute to prevent this would be awesome!

**Comment by pablo-abc** [comment]
I am guessing transforming the value inside of `onSubmit` does not work for your use case?

Adding a data attribute such as `data-felte-ignore` sounds good to me, in fact I'm surprised I have not added it yet 😅

What's your specific use case?

**Comment by greyivy** [comment]
Right. The issue is that my validation expects a boolean for a field, but I'm using a select box so felte is storing its value as a string. I'm looking to convert the value into a boolean before it hits the store so my validation succeeds.

`data-felte-ignore` sounds like a great solution! Thank you so much!

**Comment by pablo-abc** [comment]
Just added the attribute for `felte@0.7.13` and `@felte/solid@0.1.9`. It should work if you add it either to the input itself or a parent container.

If this solves your issue feel free to close this!

**Comment by greyivy** [comment]
Works beautifully, I really appreciate it!

**Comment by Deepakeon** [comment]
does this attribute works for svelte as well ? i am using felte verison 1.2.7 but unable to get it to work
