### ISSUE TITLE
validator-zod async support

### ISSUE THREAD

**Issue by basaran** [pablo-abc/felte#42]
thank you for the great library, I was wondering if there are any examples or if it is actually supported to use promise based schemas with validator-zod?

**Comment by pablo-abc** [comment]
Hello, thanks for your interest!

What's your expected use case? `validator-zod` uses `parseAsync` by default, which means use of async refinements and transforms should be fully supported. Is this what you're intending to do?

**Comment by basaran** [comment]
Thank you for getting back. I was just checking all different validators because I noticed yup handles async validation combined with the entire rule. That's,  if you have a min(5) fail, it would still call the async part.

So, I wanted to try zod to see how they do it but their documentation is lacking a bit, and I'm getting some ts errors when I try to use their examples. Most definitely I'm doing it wrong :)

**Comment by pablo-abc** [comment]
How does the data you're trying to parse look like? It's saying that you're passing `undefined` to `password` when it should be a `string`.

I can't think of a situation on which Felte would pass a promise like that to the validator, though 🤔 is this trying `Zod` alone or with Felte?

**Comment by basaran** [comment]
I was just trying to get the schema working with Felte, using the example on the documentation page, just changing the Promise part. I will try with zod alone.

**Comment by benbender** [comment]
@basaran May I ask why you would have a promise in your password-schema?

Normally you would await/resolve such a promise (f.e. for hashing the password) before passing the result into zod for validation. "Async support" in zod refers to the parse-method of zod itself being a promise and be able to run async-code inside the schema (f.e. to check with an api if a username may already be taken). It doesn't mean that zod will alter the data passed to validate against the schema or resolving any promise inside that given data.

**Comment by basaran** [comment]
Hello, I was only experimenting with zod to see how it handles the async validations like you would do with `yup` as you mentioned.

Is my understanding correct, zod doesn't do custom async validations like yup as you mentioned (lookup username in db and return false if it exists) ?

**Comment by benbender** [comment]
@basaran never actually used yup, so I'm not really qualified to compare, but yeah, zod does async, custom-validators just find. See: https://github.com/colinhacks/zod#asynchronous-refinements

**Comment by basaran** [comment]
thank you @benbender , I will look into the refinements and report back. Zod's one page documentation is a bit confusing but you gave me the right pointer. For some reason, I thought the validation was done through the `promise` option. Apparently, it seems like it's the `refinements`.

**Comment by pablo-abc** [comment]
Since this has more to do with `Zod` usage rather than `Felte`, and since Felte already does support the use of async refinements (we use `parseAsync` by default), I'm closing this. If you do find an issue with Felte's support for this, feel free to reopen the issue @basaran 😊

**Comment by basaran** [comment]
Thank you, felte is really great and flexible for different use cases. It just made working with svelte more enjoyable.
