### ISSUE TITLE
[request] Add HTMLFormElement as second argument to onSubmit()

### ISSUE THREAD

**Issue by benbender** [pablo-abc/felte#49]
At the moment, the only argument to onSubmit() is the `Data` entered to the form as a simple object.
I would like to be able to do something like the following to abstract the onSubmit-handling in different contexts:

```ts
const { form } = createForm<FormData>({
    onSubmit: async (values, form) => {
        const formData = new FormData();

        for (const key of Object.keys(values)) {
            formData.append(key, values[key]);
        }

        const result = await fetch(form.action, { // <-- dynamic use of form.action
   	    method: form.method,  // <-- dynamic use of form.method
            headers: {
                accept: 'application/json'
            },
            body: formData
        }).then((res) => res.json());

    // ...
    }
});

```

Therefor it would be great, if the `form`-object could be the second argument to `onSubmit()`.

**Comment by pablo-abc** [comment]
I see how this can be useful! I was about to ask why using `bind:this` was not an option for this. But I realise this can also be used for extending `Felte` outside of a Svelte component. (Possibly even allowing for the `onSubmit` function to be optional if we set `method` and `action` on the form element, eventually).

**Comment by pablo-abc** [comment]
This has been added in `felte@0.8.2`! I've [updated the documentation](https://felte.dev/docs/svelte/configuration-reference). I'll be closing this.
