### ISSUE TITLE
Trigger form submit programatically?

### ISSUE THREAD

**Issue by websocket98765** [pablo-abc/felte#5]
Excellent form lib!

Would it be possible to trigger a form submit event from an element outside the form?

Use case is if a form is used on a modal dialog, the submit button may be in the modal footer and outside the form element itself. 

I'm thinking something like this, but I don't know if it's possible to get a reference to the form: 
```svelte
<button type="submit" bind:this={aRefToTheForm?}>submit from outside the form</button>
```

**Comment by pablo-abc** [comment]
It is completely possible using the [`createSubmitHandler` helper function](https://felte.dev/docs#createsubmithandler)!

```javascript
const handleSubmit = createSubmitHandler();

<button on:click={handleSubmit}>Submit from outside the form</form>
```

This would not trigger a "proper" submit event but does make Felte try to submit your data as if you had submitted it in the traditional way.

**Comment by websocket98765** [comment]
Works! I read that in the docs earlier, but didn't realize it could be used for this. Makes sense. Thanks
