### ISSUE TITLE
hooks

### ISSUE THREAD

**Issue by basaran** [pablo-abc/felte#55]
Hello, would it be consistent with the purpose of felte to add a few extra event listeners like some sort of hooks. I have two different use cases.

1. Captcha preprocessing
2. Invoking animations on 3rd party UI libraries.

### `captcha` preprocessing:

At the moment, I have attached the recaptcha execution to the onSubmit handler, I also understand I could have done this the other way around, call the recaptcha first and then captchaOnSuccess, call createForm submitButtonHandler. But I figured it would be better to initiate captcha the last in case the token expires or something.

```
    onSubmit: async (values) => {
        debug("launching recaptcha");
        await recaptcha.execute();
    } /*
       │at this point all validations have passed and it
       │is okay to launch captcha sequence. rest of the
       │data submission will proceed after captcha
       │succeeds and emits onSuccess event.
       */,
```

createform -> validations -> onSubmit -> execute captha function -> onCaptchaSuccess -> doPost the form inside the callback ----> do server side validation return json -> use setError to update the form.

This is working fine, but it's a bit of flow jumping. Especially with the second round the form is submitted if there are server side validation errors. You see, for instance if I setError(phoneNumber) because it is invalid on the server side (although it looks valid syntax wise), it disrupts my use of `validate` and `$isSubmitting` and `$isValid` in my `validate()` function, which I use to display some toasts in an effort to assist the user with a visual cue.

```
    validate: (values) => {
        if ($isSubmitting && !$isValid) {
            debug("launching custom validation");
            showToast({
                title: "Incomplete Request",
                description: "Please check your inputs",
                type: "warning",
                showProgress: false,
            });
        }
    } /*
       │this is custom validation logic, we basically
       │use it to show some toast notification as a form
       │of user feedback. All validations actually
       │happen through yup validator.
       */,
```

when  `setError()` is done on the phoneNumber , it would still launch the toast, and proceed with the server post. I tried setTouch but not sure how that works. I couldn't find a way to reset the errors, the reset function appear to be resetting everything wiping out the user entered form data.

So, I think it could be helpful, if there were some `beforeSubmit`, `afterSubmit`, `beforeValidate`, `aterValidate` hooks, and some way to `clear error states` so it could be possible to trigger some css animations. Otherwise, user might feel like nothing is happening when they press the submit button (that's the reason why I put the toast there like that).

P.S the closest resetError I could do was:

```
for (const [k, v] of Object.entries(values)) {
            setError(k, false);
}
```

inside the `validate()`. But because the validate executes several times during init, and every time the during focus change, it animates the whole form. I was able to work around this by using `$isSubmitting` however.

https://user-images.githubusercontent.com/30809170/129354285-c67b6f7d-ad99-4c03-8670-06f0faef2860.mp4

**Comment by basaran** [comment]
hi, thank you very much for getting back. It's my bad, I put a whole bunch of things in one issue. Could you elaborate how to clear the touched state? I tried destructuring `touched` from `createForm` and tried setting `$touched` to `{}` but that didn't do much.

Here's how I currently use the setError at the moment. I changed a few things in my logic since last time. Instead of the toast messages, I decided to go with css animations completely (thank you for the reactive code block, it was informative, I didn't know you could do that with svelte).

https://user-images.githubusercontent.com/30809170/131207488-c4c805d5-b4c1-45ad-aced-e5158c54bd9c.mp4

You see, I'm using a custom library for the UI elements, and I need the classes physically removed and added back for the animations to kick in. I got rid of the toasters alltogether. This is what I have at the moment, and it's working nicely.

```js
    validate: (values) => {
        if ($isSubmitting) {
            for (const [k, v] of Object.entries(values)) setError(k, false);
            debug("clearing errorStates before yup");
        }
        /*
         │by resetting the errors before yup kicks in, we
         │allow css animations to initiate. Our errorStates
         │are attached to carbon's components.
         */
    } /*
       │this is custom validation logic, we can use this use
       │it kind of like a preSubmitHook, if we wrap the logic
       │inside $isSubmitting and and $isValid. This happens
       │before yup.
       */,

    extend: [validator],
    /*yup validator*/

    validateSchema: signupSchema,
    /*yup validation schema*/
```

I understand I'm not supposed to be using the `validate` block for such things, but I'm hoping this will shed some light as to my current situation. I'm using the validate property kind of like a hook.

B. Recaptcha

I'm using recaptcha v2, with the hidden button. All it gives you is a callback function once the captcha is solved by the user. This is what I have at the moment:

```js
    onSubmit: async (values) => {
        debug("executing recaptcha");

        if (!recaptcha) {
            showToast({
                title: "Preparing...",
                description: "Please try again later",
            });
            return;
        } /*
           │there is a slight chance captcha load might fail
           │and it may not be available. We should here
           │instead show a notification to the user, either
           │through a toast, or keep the return here but emit
           │a signal so captha could reload or something.
           │I ended up disabling the submit until captcha
           │is ready and loaded. So, this toast will likely
           │never launch, and it is all well.
           */

        await recaptcha.execute();
    } /*
       │at this point all validations have passed and it is
       │okay to launch captcha sequence. rest of the data
       │submission will proceed after captcha succeeds and
       │emits onSuccess event.
       */,
```

So, once the `recaptcha.execute()`, I'm already out of the felte's `onSubmit`, and no longer have access to `onError`. Instead I continue with the recaptcha callback:

```js
const onCaptchaSuccess = async (e) => {
......
......wretch api post etc...
....
        .badRequest((err) => {
            err.json.details.forEach((o) => {
                for (const [k, v] of Object.entries(o)) {
                    showToast({
                        title: "Unable to complete request",
                        description: `${k} ${v}`,
                        type: "error",
                        duration: 6200,
                        placement: "bottom-center",
                    });
                    setError(k, v);
                }
            }); /*
                 │Server errors are in Joi format. We look for
                 │details inside the returned json, manually
                 │set the felte's error states.
                 */
        })

  ```
and use `setError` once again, outside felte to update the form errors if the server error handling returned any errors. This is what I was referring to with split flow of events. I will appreciate it if you think this flow is acceptable, or if there is a way for me to handle everything inside createForm? The only way I can think of is to run the recaptcha first, and call felte's handler through captchaOnSuccess.

P.S Sorry, couldn't get back sooner. I will look into the `extending`  next. The last few days had been a bit dentist problematic for me, but I'm restoring my psychology :) and I hope you don't find my post-comment style disorienting.

**Comment by pablo-abc** [comment]
> hi, thank you very much for getting back. It's my bad, I put a whole bunch of things in one issue. Could you elaborate how to clear the touched state? I tried destructuring touched from createForm and tried setting $touched to {} but that didn't do much.

The easiest way would be to set the `touched` store to an object with the _same shape_ as your data and `false` on each prop:

```javascript
$touched = {
  field1: false,
  field2: false,
}
```

But seeing your use case, you want to add a class to your component when the form is _submitting_ and it is _not valid_ right? Would something like this work?

```svelte
<span class:animatedClass="{$isSubmitting && !$isValid}">
```

---

Regarding this, give me a while to review how reCaptcha v2 needs to be implemented. As far as I understand from what you've written, you need to submit your data _after_ an `onSuccess` callback is called. Is there a way to _promisify_ this callback? (e.g. calling a `Promise.resolve` on `onSuccess`)

**Comment by basaran** [comment]
hello, thank you again for the new snippets. Unfortunately, the UI elements do it through their own components (carbon-svelte) so, I kind of need to trigger them through the error states of each UI element.

As for the `Promise.resolve`, the google requires a callback function to pass the event where the token exists. I couldn't get far with a standard `Promise.resolve(onSuccess)` because `onSuccess` is a function?

However, I did get it to work by using a man in the middle deferral promise:

```js
let waiting;

function defer() {
    var res, rej;

    var promise = new Promise((resolve, reject) => {
        res = resolve;
        rej = reject;
    });

    promise.resolve = res;
    promise.reject = rej;

    return promise;
}
// ref: https://lea.verou.me/2016/12/resolve-promises-externally-with-this-one-weird-trick/
```

the onSuccess provided to recaptcha turned into this:

```
function onSuccess(e) {
    console.log("captcha back");
    waiting.resolve(e);
}
```

and our submitHandler now looks like this:

```js
        recaptcha.execute();
        waiting = defer();
        const p = await Promise.resolve(waiting);
        console.log("here");
        console.log(p.detail.token);
```

and devtools is telling me things are in correct order:

![image](https://user-images.githubusercontent.com/30809170/131350003-af16488d-dfbc-4b94-b2e2-723b77c08b20.png)

Would this be okay?

**Comment by pablo-abc** [comment]
Hi! May I have a sneak peak on how you're doing your animation currently? Seeing the documentation from Carbon components I don't see a way to _add_ or _remove_ classes from them. Are you checking for when the input has the `invalid` prop set? Or when the `invalidText` prop is set? I imagine there _must_ be a way to use the `isValid` and `isSubmitting` stores to trigger the animation somehow.

---

Regarding the captcha I see absolutely nothing wrong with this! But as I mentioned previously, I don't have that much experience implementing this. Anyway I actually don't see a way on which adding anything to Felte's API would make this easier without adding (what I feel is) a bit of unnecessary complexity to it. Is there anything you had in mind?

**Comment by basaran** [comment]
sure thing, here's a svelte input:

```html
<div class="phoneContainer__phoneInput">
      <TextInput
          noLabel
          name="phoneNumber"
          autocomplete="phoneNumber"
          bind:value={$data["phoneNumber"]}
          invalid={$errors["phoneNumber"]}
          invalidText={$errors["phoneNumber"]} />
</div>
```

and I added a little override for their error class:

```css
.bx--form-requirement {
    position: absolute;
    margin-top: 42px;
    margin-left: 2px;
    animation: shake 0.2s;
}
```

---

I don't think there is much we can do as far as recaptcha goes. I was able to refactor everything into `onSubmit` with the deferred promise approach and I was also able to trigger the animations with reactivity without hacking the `validate` method or messing around with setError.

```js
/*------------------------------------------------ reactivity --*/

$: {
    if ($isSubmitting && !$isValid) {
        for (const [k, v] of Object.entries($touched)) {
            $touched[k] = false;
        }
    }
} /*
   │We reset the touched store whenever an
   │invalid form is submitted to trigger shake
   │animations on error text.
   */
```

Server side errors are now handled inside `onError`:

```js
await wretch(api.signup)
   .post(postData)
   .badRequest((err) => {
        debug("bad response from server");
        throw err;
    });
...
onError: (err) => {
    err.json.details.forEach((o) => {
        for (const [k, v] of Object.entries(o)) {
            //showToast()
            $errors[k] = v;
        }
    }); /*
         │Server errors are in Joi format. We
         │look for details inside the returned
         │json, manually set the felte's error
         │states.
         */
},
```

---

At this point, I think my request for hooks and resetting states is no longer relevant.  I think I did pretty much everything with this form that I could possibly need with the majority of forms (except async client side validation but it will be fine)  I will need in the future and can proceed with the rest of my development. All third party libraries were successfully `glued` together.

[x] disable form controls while recaptcha is initializing.
[x] enable form after recaptcha injects
[x] disable form after Submit (preventDefault doesn't work with 3rd party components)
[x] detect if/when recaptcha modal pops
[x] keep submit logic inside felte (deferred promise)
[x] enable form controls back if recaptcha was canceled by user
[x] attach felte to carbon components
[x] reactively trigger client side errors
[x] use yup for schema validation
[ ] client side async validation, custom validation logic besides yup
[x] pull back server side errors back into felte
[x] checkbox validations
[x] use setField to manipulate form $data externally.
[x] use yup with .addMethod for custom rules.
[x] use input events with carbon (i.e capitalize fullName)

and there should be plenty of information available here for the next wondering soul :) Thank you for the library and all your assistance.

**Comment by pablo-abc** [comment]
I'm glad you managed to make it work!

Just a note here. Felte _does_ handle client side async validation. You can return a promise from the `validate` function. It does not handle callbacks since they're usually easy to convert to promises. Is there anything else that is missing from this that I am not considering?

Regarding Yup, I designed Felte so you could use any validation strategy you want. E.g. I've made [adapters for `yup`, `zod` and `superstruct`](https://felte.dev/docs/svelte/validators) and, in theory, it is possible to create your own adapters with the same API to [extend Felte](https://felte.dev/docs/svelte/extending-felte).

**Comment by basaran** [comment]
yep, and I made it all work with Felte, used yup and will use the validate method when the need arises :) Thank you again for your time.
