### ISSUE TITLE
t2.addValidator is not a function

### ISSUE THREAD

**Issue by basaran** [pablo-abc/felte#59]
Hello,

I did a cleanup on my node_modules and did a fresh yarn install on the latest svelte. Compiler is throwing as follows:

```
proxy.js:19 TypeError: t2.addValidator is not a function
    at n (index.ts:42)
    at index.mjs:1
    at Array.map (<anonymous>)
    at stores (index.mjs:1)
    at w (index.mjs:1)
    at instance (SignupForm.svelte:380)
    at init (index.mjs:1791)
    at new SignupForm (SignupForm.svelte:363)
    at createComponent (svelte-hooks.js:136)
    at SignupForm.targetCmp.$replace (svelte-hooks.js:183)
```

```
  vite v2.5.10 dev server running at:

  > Local:    http://localhost:4000/

  SvelteKit v1.0.0-next.174
```

I think it's the `@felte/validator-yup` somehow not working anymore. I will keep looking.

**Comment by pablo-abc** [comment]
Hi! Since we are still pre v1.0.0, there might be some breaking changes in between minor versions. Make sure you're using felte@^0.8.0 if you're using the latest version of validation-yup!

**Comment by basaran** [comment]
Hi :)

I just tested the previous versions, and they worked:

```
"felte": "0.7.13",
"@felte/validator-yup": "0.2.6",
```

Let me update the package.json real quick.

**Comment by basaran** [comment]
```
"felte": "^0.8",
"@felte/validator-yup": "^0.2.6",
```
worked out fine.

I wonder though, why hasn't yarn picked up the latest when I had done the `rm -Rf node_modules` and yarn upgrade and yarn install.

Well, anyhow, this works, I'm closing. Thank you for getting back so quickly. Have a great rest of the weekend.
