### ISSUE TITLE
dom-reporter input focus

### ISSUE THREAD

**Issue by basaran** [pablo-abc/felte#66]
Hello again :)

It appears the dom reporter is looking for `data-felte-validation-message`.

The issue I'm having with this `now it took two days of my life` component is that, even I can inject the attribute `data-felte-validation-message` into it, it becomes out of sync, so when the dom-reporter is doing the querySelect on the form, it can't find it at that time.

I tested the theory with importing `tick().then(() => { ...focus })` into the dom-reporter, it was partially sucessful. setTimeout was the most successful.

I'm just asking so I learn, what do you think about having the dom-reporter accept an onSubmitError callback in the options and if it is not provided then execute the standard logic?

**Comment by pablo-abc** [comment]
I'm struggling to understand what's happening here. Are you trying to use the `reporter-dom` package with a custom field? (not an `input`, `textarea`, etc). Do you have an example of what you're trying to achieve? (a Code Sandbox or Svelte REPL example would be nice, just note that if you're using `yup`, it won't work on the Svelte REPL).

**Comment by basaran** [comment]
helloo :) yes it is with the custom components and not just this one I was working on but also I tested with carbon too. I will get you a repository as soon as I can. That would be the easiest, should had done that to begin with.

**Comment by pablo-abc** [comment]
With Felte v1 [there's a new and better way to handle custom form controls where user's don't interact directly with native HTML controls](https://next.felte.dev/docs/svelte/custom-form-controls#using-createfield). This shouldn't be an issue from now. Here's the example from the docs:

```svelte
<script>
  import { createField } from 'felte';

  export let name;

  const { field, onInput, onBlur } = createField(name);

  function handleInput(e) {
    onInput(e.currentTarget.innerText);
  }
</script>

<div
  use:field
  on:input={handleInput}
  on:blur={onBlur}
  aria-labelledby={labelId}
  role="textbox"
  contenteditable="true"
  tabindex="0"
  />
```

Note that the element where you use the action has to be focusable. I'm also hoping to improve a bit the way Felte finds invalid inputs, but this works pretty well now!
