### ISSUE TITLE
docs: Add loose email validation to manual validation example

### ISSUE THREAD

**Issue by websocket98765** [pablo-abc/felte#7]
I couldn't find this in the docs to PR, but thought this might improve the [manual validation](https://felte.dev/docs#validation) example a bit:

from:
`if (!values.email) errors.email = 'Must be a valid email';`

to:
`if (! /.+\@.+\..+/.test(email)) errors.email = 'Must be a valid email';`

**Comment by pablo-abc** [comment]
That makes sense. I'll make the change right away!

For reference, the docs are [here](https://github.com/pablo-abc/felte-docs), but I'm looking to move them into the monotipo soon.
