### ISSUE TITLE
$isSubmitting value inside template

### ISSUE THREAD

**Issue by basaran** [pablo-abc/felte#71]
Hello,

As per your previous recommendation #55 , I decided to try your method to trigger add/remove of CSS classes on submit:

So I have this code:

```
<label for="city" class:animator={$isSubmitting && !$isValid}>City</label>
```

But the result of `$isSubmitting && !$isValid` always return false. But I see the class property flashing in the dev console. It just seems `$isSubmitting` is always false.

Meanwhile `!$isSubmitting && !$isValid` appears to be doing what I need. Is this expected behaviour?

**Comment by pablo-abc** [comment]
As far as I can tell [the way these stores behave is working properly](https://svelte.dev/repl/319db54930ad4fb8854d198567c99ac9?version=3.44.1). Maybe it was a misunderstanding on my part on #55. But yes, a combination of those stores should work for you. The difference between both conditionals is that:

- `$isSubmitting && !$isValid`: would _add_ the class for the few milliseconds it takes to trigger the `submit` function.
- `!$isSubmitting && !$isValid`: would _remove_ the class for the few milliseconds it takes to trigger the `submit` function.

So it depends on what you need. If the second approach is working for you, then I guess that's how it should be!
