### ISSUE TITLE
[Question] Trigger validation reporter without submitting form

### ISSUE THREAD

**Issue by half2me** [pablo-abc/felte#74]
Hi,

In my use case I need to be able to trigger validation before submitting the form. For example, after a user finishes typing into one of the inputs, I want to immediately show if its valid or not, without waiting until the form is submitted.

I tried the `validate()` function, which seems to do exactly this, but I find that it doesn't trigger the reporters. So, while I do get the validation status in js, the DOM won't update nicely with the error messages (like it does on form submission). Is it possible to trigger this behaviour without actually submitting the form?

**Comment by pablo-abc** [comment]
Hey,, @half2me! Unless I'm not understanding correctly you issue, what you describe should already be the default behaviour of Felte. As soon as the user finishes typing and the input is blurred, the error state should appear. Is there anything I'm missing?

The reason why we wait until _blur_ to display errors is that it seems to be widely accepted now that showing validation errors _while_ typing is bad UX (specially for users using a screen-reader).

**Comment by half2me** [comment]
Waiting until blur is not my issue. My issue is that the reporter does not show the error on blur. The `$errors` store correctly gets populated, but my reporter doesn't change anything on the dom until I submit the form. I'm using `@felte/reporter-cvapi`

**Comment by pablo-abc** [comment]
So, that reporter's only purpose is to set the input's to they're invalid state. So it will behave just as the default's browser validation works (which I do believe is more or less how you described. Until `submit` happens). Felte _does_ update the validity state of the inputs immediately, though. So if you want to have this kind of behaviour (which differs from the browser's one), you should use one of the other reporter packages.

The reporter package that allows for most flexibility is `reporter-svelte`, while if you want a similar way to present your errors (via tooltips), `reporter-tippy` does that for you!

**Comment by half2me** [comment]
@pablo-abc thank you for the clarification. I didn't know that this behaviour was the browser's implementation.
I will switch to reporter-tippy probably anyway, so that shouldn't be an issue.

Thank you so much.

**Comment by pablo-abc** [comment]
Perfect! I'll be closing this issue, then. If you have any issues with that reporter feel free to open another issue.
