### ISSUE TITLE
Add integration for validation framework Vest

### ISSUE THREAD

**Issue by taffit** [pablo-abc/felte#76]
[Vest](https://github.com/ealush/vest) got a lot of traction lately as well as a lot of positive comments and mentions (e. g. [here](https://codechips.me/form-validation-svelte-vest/)). It was also subject to a talk on the latest Svelte Summit ([link to talk](https://www.youtube.com/watch?v=1Df-9EKvZr0&t=18535s))

Having a native integration with felte and Vest would be great (as you mention it to add a new issue if some validation framework is missing in your docs, I took the freedom to create one ;-) ).

Btw, thank you for creating a great library.

**Comment by pablo-abc** [comment]
Big thanks to @loremaps. His package just got published under `@felte/validator-vest`! You can try it out

**Comment by taffit** [comment]
Wow, THAT was quick. Thank you @loremaps for this more-than-fast implementation. Will try it out today.
