### ISSUE TITLE
Set `isSubmitting` to `false` again automatically, if validation errors exist.

### ISSUE THREAD

**Issue by websocket98765** [pablo-abc/felte#9]
I disabled my submit button like this, to prevent users clicking it twice while an HTTP POST is in flight.

```svelte
<button type="submit" disabled={$isSubmitting}>submit</button>
```
But found a problem: if a client side error message exists, it's never re-enabled. 

It should be re-enabled as soon as the error messages are displayed, so user can click submit again after fixing their errors.

**Comment by pablo-abc** [comment]
Fixed (and added tests to prevent this from happening again) in [felte@0.5.5](https://github.com/pablo-abc/felte/blob/main/packages/felte/CHANGELOG.md#055)!
