### ISSUE TITLE
No matching version found for @felte/common@1.0.0-next.7. when installing @felte/validator-zod

### ISSUE THREAD

**Issue by winston0410** [pablo-abc/felte#93]
With the following dependencies:

```
	"dependencies": {
		"felte": "next",
        "@felte/validator-zod": "next",
	}
```

I got the following error:

```
nix-shell ❯ npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @felte/common@1.0.0-next.7.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hugosum/.cache/npm/_logs/2022-01-18T12_50_44_028Z-debug.log
```

I think that dependency in `validator-zod` is off right now.

**Comment by pablo-abc** [comment]
Hi, @winston0410! I'm unable to reproduce this in a fresh project. Any more information you have regarding this? That version of `@felte/common` _is_ [on npm](https://www.npmjs.com/package/@felte/common).

**Comment by winston0410** [comment]
@pablo-abc I have removed the cache for npm and it worked. Properly npm treated `next` tag as the same version, and it has given me the older `next` in cache. Closing this now.
