### ISSUE TITLE
`warnings` store has a different signature with `errors`

### ISSUE THREAD

**Issue by winston0410** [pablo-abc/felte#95]
Using the following code, I am able to get a `warnings` store, but it is empty, unlike `errors` where key is field name and value is the error message 

```javascript
  	import * as z from 'zod';
	import { validator } from '@felte/validator-zod';
	import { createForm } from 'felte';

	const warningSchema2 = z.object({
		'convert-characters': z.string().nonempty()
	});
    
    const { warnings } = createForm({
        onSubmit: () => {},
        warningSchema: warningSchema2,
        extends: validator
    })

    console.log($warnings)

```

I am using `0.9.0` for `felte` and `0.3.8` for `@felte/validator-zod`. Is that the expected behavior for `warnings`?

**Comment by pablo-abc** [comment]
I think I see a typo on your configuration? Should be `warnSchema` instead of `warningSchema`. If this still does not work for you, a CodeSandbox or REPL reproduction would be nice! But yeah, initially `warnings` will be just a `{}` until there are some warnings set.

**Comment by winston0410** [comment]
Right it was my typo there, and switching to `warnSchema` solved this issue. I am not sure why I don't get any typing error from typescript. Closing this issue.
